# Generated by Django 5.1.2 on 2024-10-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_planner_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default='0'),
        ),
    ]
