# Generated by Django 5.1.2 on 2024-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_planner_api', '0002_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.AddField(
            model_name='destination',
            name='end_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='destination',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
