# Generated by Django 5.1.2 on 2024-10-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_planner_api', '0003_remove_destination_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='city_name',
        ),
    ]
