# Generated by Django 5.1.2 on 2024-10-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_planner_api', '0004_rename_name_destination_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='city_name',
            new_name='name',
        ),
    ]
